swagger: "2.0"
info:
  version: "1.0.0"
  title: Transactions API
schemes:
  - https
basePath: /api/v1 # Chemin de base de l'API
paths:
  /accounts:
    get:
      summary: Get all accounts
      description: Get all user accounts from my API.
      security:
        - BearerAuth: []
      responses:
        200:
          description: Get all account Successfully
        400:
          description: Get all account Unauthorized
        501:
          description: Server error
  /accounts/{account_id}/transactions:
    get:
      summary: Get all transactions of an account
      description: Get all transactions associated with a specific account from my API.
      security:
        - BearerAuth: []
      parameters:
        - name: account_id
          in: path
          description: The ID of the account for which to fetch transactions.
          required: true
          type: integer
      responses:
        200:
          description: Get all transactions Successfully
        400:
          description: Get all transactions Unauthorized
        404:
          description: Account not found
        501:
          description: Server error
  /transactions/{transaction_id}/category:
    put:
      summary: Edit a transaction's category
      description: Edit the category of a specific transaction in my API.
      security:
        - BearerAuth: []
      parameters:
        - name: transaction_id
          in: path
          description: The ID of the transaction to edit.
          required: true
          type: integer
        - name: category
          in: body
          description: The new category to assign to the transaction.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Transaction's category edited successfully
        400:
          description: Edit transaction Unauthorized
        404:
          description: Transaction not found
        501:
          description: Server error
  /transactions/{transaction_id}/note:
    post:
      summary: Add a note to a transaction
      description: Add a note to a specific transaction in my API.
      security:
        - BearerAuth: []
      parameters:
        - name: transaction_id
          in: path
          description: The ID of the transaction to add a note.
          required: true
          type: integer
        - name: note
          in: body
          description: The note to add transaction.
          required: true
          schema:
            type: string
      responses:
        200:
          description: Note added to the transaction successfully
        400:
          description: Add note to transaction Unauthorized
        404:
          description: Transaction or account not found
        501:
          description: Server error
  /transactions/{transaction_id}/note/{note_id}:
    delete:
      summary: Delete a note of a transaction
      description: Delete a note to a specific transaction in my API.
      security:
        - BearerAuth: [] # Indique que l'authentification se fait avec un token Bearer
      parameters:
        - name: transaction_id
          in: path
          description: The ID of the transaction to delete a note.
          required: true
          type: integer
        - name: note_id
          in: path
          description: The ID of the note you want delete.
          required: true
          type: integer
      responses:
        200:
          description: Note dleted of the transaction successfully
        400:
          description: Deleted note to transaction Unauthorized
        404:
          description: Transaction or note not found
        501:
          description: Server error
securityDefinitions:
  BearerAuth: # Définition de la sécurité pour le token Bearer
    type: apiKey
    name: Authorization
    in: header
